#The new password you want for guacadmin
guacadmin_password: changeme

#The username of the guacuser
guac_user: delphix

#The password of the guacuser
guac_user_password: changeme

#The password used to configure VNC
vnc_password: changeme

#The delphix_admin_password for the tester
delphix_admin_password: changeme

domain_suffix: delphix.local

lab_systems:
  - tooling
  - delphixengine
  - datical-server
  - proddb
  - devdb
  - devweb
  - prodweb
  - testweb

docs_host: "18.236.74.213"

docs_ver: "204"

wp_text: "{{ lookup('template', 'credentials.j2') }}"

#To pull in Postgres Plugin from S3
## Below commented out until Updated Plugin Code is released
# aws_access_key_id: "{{ lookup('env','S3_AWS_ACCESS_KEY_ID') }}"
# aws_secret_key: "{{ lookup('env','S3_AWS_SECRET_ACCESS_KEY') }}"
# s3_bucket: "{{ lookup('env','S3_BUCKET') }}"
# s3_object_path: "{{ lookup('env','S3_OBJECT_PATH') }}"
# postgres_plugin_archive: Plugin_postgreSQL_1.3.0.zip